version: '3'

services:

    avm:
        build:
            context: .docker
            dockerfile: Dockerfile
            args:
                - "DOCKER_USER=${DOCKER_USER}"
                - "DOCKER_USER_ID=${DOCKER_USER_ID}"
        image: "avm:1.0"
        restart: "no"
        user: "${DOCKER_USER}"
        environment:
            - "SSH_AUTH_SOCK=/ssh-agent"
            - "ANSIBLE_DEFAULT_VERSION=${ANSIBLE_DEFAULT_VERSION}"
        volumes:
            - "$PWD:/home/docker"
            - "~/.ssh/known_hosts:/home/${DOCKER_USER}/.ssh/known_hosts:ro"
            - "$SSH_AUTH_SOCK:/ssh-agent"
        working_dir: "/home/docker"
